import std
import std.error
import std.process

proc main() {
    con result = divide(2, 0) ? {
        std.println("error: " & this.msg)
        process.exit(1)
    }
    std.println(result)
}

func divide(a, b) ! {
    if b == 0 {
        throw error.new("can not divide by zero!")
    }
    return a / b
}
